# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
pool:
 name: Default

stages:
  - stage: Deploy
    displayName: 'Deploy Web App'
#    dependsOn: Build
#    condition: succeeded()
    jobs:
    - deployment: DeploymentJob
      environment: VM-JAVA
      strategy:
        runOnce:
          deploy:
            steps:
        
              - task: DownloadPipelineArtifact@2
                inputs:
                  buildType: 'specific'
                  project: '4778fa29-d1ca-4971-aaf1-5416a8a4d305'
                  definition: '5'
                  buildVersionToDownload: 'latest'
                  targetPath: '$(Pipeline.Workspace)'
              - task: CopyFilesOverSSH@0
                inputs:
                 sshEndpoint: 'ssh-cd-dev'
                 sourceFolder: '$(Pipeline.Workspace)/drop/webapp/target'
                 contents: '**/*.war'
                 targetFolder: '/opt'
                 readyTimeout: '20000'
            
