# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
pool:
 name: Default

stages:
  - stage: Deploy
    displayName: 'Deploy Web App'
    dependsOn: Build
    condition: succeeded()
    jobs:
    - deployment: DeploymentJob
      environment: VM-JAVA
      strategy:
        runOnce:
          deploy:
            steps:
            - task: PublishPipelineArtifact@1
              inputs:
               targetPath: '$(Pipeline.Workspace)'
               artifact: 'drop'
               publishLocation: 'pipeline'
            
